name: Build and run ROS2 tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        rosdistro: [ humble ]

    runs-on: ubuntu-latest

    container:
      # There don't seem to be ROS perception docker images for ros2 yet, so we
      # use the base imageand install the rest of the dependencies using rosdep
      # each time.
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
    - uses: actions/checkout@v2
      with:
        path: src/ros2_topic_sample

    - name: Install dependencies
      run: rosdep update --include-eol-distros && apt-get update && rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}

#     - name: Install diagnostic-updater
#       run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

    - name: Build tests
      id: build_test
      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon build --event-handlers console_cohesion+
      continue-on-error: true

    - name: build_test command success
      if: steps.build_test.outcome == 'success'
      run: echo "result - success"

    - name: build_test command failure
      if: steps.build_test.outcome == 'failure'
      run: echo "result - failure" && exit 1

    - name: Run tests
      id: run_test
      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon test --event-handlers console_cohesion+ && colcon test-result
      continue-on-error: true

    - name: run_test command success
      if: steps.run_test.outcome == 'success'
      run: echo "result - success"

    - name: run_test command failure
      if: steps.run_test.outcome == 'failure'
      run: echo "result - failure" && exit 1

  check_status:
    needs: build_and_test
    if: ${{ needs.build_and_test.result != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Status to Failure
        run: exit 1
